image: node:18-alpine

pipelines:
  default:
    - step:
        name: Run Telegram Bot via Tor
        caches:
          - node
        script:
          - echo "Installing dependencies..."
          - apk add --no-cache tor curl

          - echo "Starting Tor in the background..."
          - tor &  # Start Tor service

          - echo "Waiting for Tor to initialize..."
          - sleep 15  # Ensure Tor is ready

          - echo "Installing Node.js dependencies..."
          - npm install  # Install dependencies from package.json

          - echo "Starting bot with Tor..."
          - TELEGRAM_BOT_TOKEN="7909374116:AAFShC2Kc7pqxJaBoNTJLWDCbCoRAldh8Nc" torsocks node bot.js
           
