image: node:latest  # Use Node.js for the bot
size:2x
pipelines:
  default:
    - step:
        name: Build & Run Bot
        script:
          - apt-get update && apt-get install -y gcc  # Install GCC for compiling
          - gcc -o venompapa rspapa.c -lpthread             # Compile C helper tool
          - chmod +x helper_binary                    # Ensure executable permission
          
          - npm install                               # Install Node.js dependencies
          - node bot.js                               # Run the Telegram bot
